### ISSUE TITLE
When stress testing pexlock, I found a problem with punlock

### ISSUE THREAD

**Issue by AquariusPower** [ShellShoccar-jpn/misc-tools#6]
I was stress testing concurrent unlock and found some problems.

To see the problem happening run this test like this:
`bSafePunlock=false pexlock.tst2.sh`
It will end much faster than expected, and it may try to unlock a lock created after the dead pid was detected, it should unlock the lock only if it is of the dead pid.

I think punlock should also be run exclusively for the same lock id.
And in case the punlock's lock remains there for any reason, it should be cleaned after some time?

`cat >pexlock.tst2.sh;chmod +x pexlock.tst2.sh`
```
#!/bin/bash

# pkill -fe "pexlock.tst.sh --dummy" #help use this if needed
# while true;do pcllock -d /tmp/plock/ -w 3 -l 1;sleep 1;done #help I tried using this on another terminal, but it apparently does not consider if the pid related to the lock is still running.

if [[ -z "${1-}" ]];then
  egrep "[#]help" $0
  echo
  read -n 1 -p PressAKeyToStart
  echo
  
  punlock safe_punlock_tstLock #cleanup from previous run if needed
  : ${nRunSelfTimes:=10} #help DO NOT USE A TOO HIGH VALUE, I tried with 100 and the machine got weird (100% cpu usage being 65% system but htop and top wont show what is using these 65% and I had to reboot!)
  for((i=0;i<$nRunSelfTimes;i++));do $0 --dummy&:;done; 
  exit 0;
fi

strLockId=tstLock
flLockId=/tmp/plock/tstLock; #flLock
mkdir -p /tmp/plock/;
: ${bShowStatus:=false} #help if false, lowers verbosity
: ${nRunSubshellTimes:=6} #help 6*10, with 1s+Random1s work, it all should take from 1 to 2 minutes to complete.
: ${bSafePunlock:=true} #help set to false to see the "PROBLEM!" below happen, it will also last only about 10s instead of the 1-2 minutes
for((i=0;i<$nRunSubshellTimes;i++));do 
  (
    strThisId=""
    while ! pexlock -d /tmp/plock -w 1 $strLockId 1>/dev/null 2>/dev/null;do
      # tries to unlock the lock created by the other process
      if ! pexlock -d /tmp/plock -w 1 safe_punlock_tstLock 1>/dev/null 2>/dev/null;then continue;fi
      
      if [[ ! -f "$flLockId" ]];then punlock safe_punlock_tstLock;continue;fi
      
      nOtherPid=`cat $flLockId 2>/dev/null`;
      if [[ -z "$nOtherPid" ]];then punlock safe_punlock_tstLock;continue;fi
      
      if $bShowStatus && [[ -d /proc/$nOtherPid ]];then echo "`date +"%H%M%S.%N"` ($$:$i) waiting '$(ps --no-headers -o cmd -p $nOtherPid)' end";punlock safe_punlock_tstLock;continue;fi
      
      # releases the lock created by a now dead pid
      if [[ "`cat $flLockId`" == $nOtherPid ]];then
        # from the cat above to the punlock below, the file may still have changed!!!
        echo "`date +"%H%M%S.%N"` ($$:$i) Removing lock of dead pid $nOtherPid"
        punlock $flLockId; # this should check if the PID stored on it was the same pexlock checked above!
      else
        echo "`date +"%H%M%S.%N"` ($$:$i) >>>>> PROBLEM! AVOID REMOVING A LOCK CREATED BY A NEW PROCESS!!! <<<<<"
      fi
      punlock safe_punlock_tstLock;
    done;
    echo "`date +"%H%M%S.%N"` ($$:$i) WORKING $$";
    sleep 1.$RANDOM;
    punlock $flLockId;
  )&:;
done

```

Obs.: this is not a real testcase, this is concurrent stress test, so these problems may never happen in a normal/real test case.

PS.: did I do some mistaken implementation in this code? if so, there may have no problem! xD

**Comment by AquariusPower** [comment]
flock seems to fail sometimes too, see:
https://gist.github.com/AquariusPower/c5fe6fcc55f1c55753176c05f9a15ca4
EDIT: this was my fault, the script was the lock file, and editing it (and saving) released the lock, as the editor creates a new file!

**Comment by colrichie** [comment]
@AquariusPower :
Thanks for your test. I'm concerned about your report. But, I can't catch the problem you asserted. There are two favors what I want to ask you.

# 1
Before the discussion about the problem, I'd like you to make sure that the shell script "pexlock.tst2.sh" has no mistake.

For instance, the script uses the "punlock" command with neither the -d option nor the environment variable "PLOCKDIR" while it uses "pexlock" with the -d option. So, I don't think that both the commands read/write the same directory. Isn't that point a cause of the problem?

# 2
And, could you tell me the expected behaviors when the script succeeds and fails? The message "PROBLEM! AVOID REMOVING A LOCK CREATED BY A NEW PROCESS!!!" is for failure, right?

**Comment by AquariusPower** [comment]
> For instance, the script uses the "punlock" command with neither the -d option nor the environment variable "PLOCKDIR" while it uses "pexlock" with the -d option. So, I don't think that both the commands read/write the same directory. Isn't that point a cause of the problem?

good point, I may have coded something not as expected!
I think you may be right, it apparently was just missing `-d /tmp/plock`
